name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库的代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Go 环境
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.9'

      # 安装依赖
      - name: Install dependencies
        run: go mod download

      # 运行测试
      - name: Run tests
        run: go test ./... -v